# CircleCI build config to test different versions of Singuarity
version: 2.1

orbs:
  singularity: singularity/singularity@1.0.9

workflows:
  version: 2
  test:
    jobs:
      - run-spython-ci-tests: &base_job
          filters:
            branches:
              ignore: master
          name: "Latest Singularity - Python 3"
          run-linter: false
          singularity: 3.5.0
          singularity-3: true
      - run-spython-ci-tests:
          <<: *base_job
          name: "Singularity 3.2.1 - Python 3"
          singularity: 3.2.1
          run-linter: true # run linter once, must be Python 3
      - run-spython-ci-tests:
          <<: *base_job
          name: "Singularity 3.1.0 - Python 3"
          singularity: 3.1.0
      - run-spython-ci-tests:
          <<: *base_job
          name: "Singularity 2 - Python 3"
          singularity: 2.6.1
          singularity-3: false

waitforapt: &waitforapt
  name: Remove cloud init lock
  command: |
      while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 10; done
      while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do echo 'Waiting for autoupdates to complete...'; sleep 10; done
      echo 'Waiting for instance to really be ready...'
      sleep 30
      sudo rm -rf /var/lib/apt/lists/lock
      sudo rm /var/lib/dpkg/lock && sudo dpkg --configure -a


install_spython: &install_spython
  name: install spython
  command: |
      pip uninstall spython --yes || echo "Not installed"
      python --version
      python setup.py install

commands:
  install_dependencies:
    steps:
      - run: |
          PYTHON_VERSION=3
          CONDA_PATH="$HOME/conda/Python${PYTHON_VERSION}"
          echo 'export PATH="'"$CONDA_PATH"'/bin:$PATH"' >> "$BASH_ENV"
          source "$BASH_ENV"
          if [ ! -d "$CONDA_PATH" ]; then
              CONDA_SCRIPT=Miniconda${PYTHON_VERSION}-latest-Linux-x86_64.sh
              wget https://repo.anaconda.com/miniconda/$CONDA_SCRIPT
              /bin/bash $CONDA_SCRIPT -b -p $CONDA_PATH
          else
              echo "Miniconda is already installed, continuing to build."
          fi
          python --version
          [ $(python -c'import sys;print(sys.version_info.major)') -eq $PYTHON_VERSION ]

          pip install --upgrade pytest
          pip install black || true

run_linter: &run_linter
  name: run linter
  command: |
      cd ~/repo
      black --check spython

test_spython: &test_spython
  name: Test Singularity Python
  command: pytest ~/repo/spython

jobs:
  run-spython-ci-tests:
    parameters:
        run-linter:
          type: boolean
          default: false
        singularity:
          type: string
          description: "Singularity version"
        singularity-3:
          type: boolean
          description: "Set to true for singularity 3, false for singularity 2"
          default: true
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys: v2-dependencies
      - install_dependencies
      - run: *waitforapt
      - when:
          condition: << parameters.singularity-3 >>
          steps:
            - singularity/install-go:
                go-version: "1.13"
            - singularity/debian-install-3:
                singularity-version: << parameters.singularity >>
      - unless:
          condition: << parameters.singularity-3 >>
          steps:
            - singularity/debian-install-2:
                singularity-version: << parameters.singularity >>
      - run: *install_spython
      - save_cache:
          paths:
            - ~/conda
          key: v2-dependencies
      - when:
          condition: << parameters.run-linter >>
          steps:
            - run: *run_linter
      - run: *test_spython
