#!/bin/bash

sudo apt-get update && sudo apt-get install -y wget git build-essential squashfs-tools \
                                                    libtool \
                                                    autotools-dev \
                                                    automake \
                                                    autoconf \
                                                    uuid-dev \
                                                    libssl-dev


sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers

echo "PYTHON VERSION"
which python

python setup.py sdist && python setup.py install

# Install Singularity (development)
cd /tmp && git clone https://github.com/singularityware/singularity.git && cd singularity && ./autogen.sh && ./configure --prefix=/usr/local && make && sudo make install

