#!/bin/bash
sudo apt-get install -y squashfs-tools

if [ "${PYTHON_VERSION}" == "2" ];
then
    python -m unittest discover -s $TRAVIS_BUILD_DIR/spython/tests/ -p '[t|T]est*.py'
else
    python3 -m unittest discover -s $TRAVIS_BUILD_DIR/spython/tests/ -p '[t|T]est*.py'
fi
