name: spython-ci

on:
  push:
    branches:
      - master
  pull_request: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Spelling
        uses: crate-ci/typos@592b36d23c62cb378f6097a292bc902ee73f93ef # version 1.0.4
        with:
          files: ./spython ./.docs ./README.md

      - name: Setup black linter
        run: conda create --quiet --name black pyflakes

      - name: Lint python code with black
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          pip install black
          black --check spython

      - name: Check unused imports with pyflakes
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          pyflakes spython/oci spython/image.py spython/instance spython/main

  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - uses: singularityhub/install-singularity@develop
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest semver pytest-runner requests

      - name: Run unit tests
        run: pytest
